version: '3.3'
services:
  web:
    build:
       context: ./coffee-ui
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./coffee-ui/resources:/usr/share/nginx/html
    networks:
      - frontend-network
  backend:
    build:
      context: ./coffee-service
      dockerfile: Dockerfile-dev
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
  db:
    image: "mysql:8.0.20"
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'coffee_db'
      MYSQL_USER: 'coffee'
      MYSQL_PASSWORD: 'coffee'
      MYSQL_ROOT_PASSWORD: 'coffee'
    ports:
      - '3306:3306'
    networks:
      - backend-network

networks:
  backend-network:
  frontend-network:
